default:
  image: golang:1.10-alpine3.7

stages:
  - build

build:
  stage: build
  script:
    - apk add --no-cache curl git
    - curl -sSL https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o /go/bin/dep
    - chmod +x /go/bin/dep
    - go build