default:
  image: golang:1.10-alpine3.7

stages:
  - build

build:
  stage: build
  script:
    - export GOPATH="${HOME}/.go"
    - export GOROOT="$(brew --prefix golang)/libexec"
    - export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"
    - test -d "${GOPATH}" || mkdir "${GOPATH}"
    - go build